VenusProtocol/isolated-pools

- hardhat.config.ts
> fix etherscan-verify config for testnet

- contracts/Pool/PoolRegistry.sol
- tests/hardhat/PoolRegistry.ts
> fix: poolmetadata spelling and add event to tests

- tests/hardhat/Fork/RiskFund.ts
- tests/hardhat/PoolRegistry.ts
- tests/hardhat/ProtocolShareReserve.ts
- tests/hardhat/Rewards.ts
- tests/hardhat/Shortfall.ts
- tests/hardhat/UpgradedVBEP20.ts
- tests/hardhat/lens/PoolLens.ts
These ignores were solved with updates to typechain tooling
> chore: remove typescript ignores

- package.json
Add missing script to copy contracts for compilation
> fix: include copy contracts in package

- contracts/Pool/PoolRegistry.sol
- deploy/003-deploy-pools.ts
- hardhat.config.ts
- tests/hardhat/Fork/RiskFund.ts
- tests/hardhat/PoolRegistry.ts
- tests/hardhat/Rewards.ts
- tests/hardhat/UpgradedVBEP20.ts
- tests/hardhat/lens/PoolLens.ts
Add parameter for setting minimum liquidatable collateral when creating pool
> Add min liquidatable collateral to create pool

- contracts/ComptrollerInterface.sol
- contracts/Lens/PoolLens.sol
- tests/hardhat/lens/PoolLens.ts
Adds minLiquidatableCollateral to values returned by pool lens when fetching pool data
> Add minLiquidatableCollateral to pool lens

- .gitignore
- tests/hardhat/lens/PoolLens.ts
>  correctly ignore DS_Store

- contracts/RiskFund/ProtocolShareReserve.sol
- contracts/RiskFund/ReserveHelpers.sol
- tests/hardhat/Fork/RiskFund.ts
- tests/hardhat/ProtocolShareReserve.ts
This PR contains:
- Resolved the comments for the [PR#85](https://github.com/VenusProtocol/isolated-pools/pull/85).
> Fix Review comments for PR#85.

- contracts/Comptroller.sol
- contracts/test/ComptrollerHarness.sol
- contracts/test/ComptrollerScenario.sol
Orders comptroller definitions
Add complete natspec
> Organize comptroller and update Natspec

- contracts/Comptroller.sol
- contracts/ComptrollerStorage.sol
- contracts/test/ComptrollerHarness.sol
- contracts/test/ComptrollerScenario.sol
- deploy/003-deploy-pools.ts
- tests/hardhat/Comptroller/assetsListTest.ts
Updates borrow cap so 0 means borrowing is not allowed and maxint256 is unlimited borrowing
> Set unlimited borrow cap as maxint

- package.json
Bumps version to 0.0.13 for release
> chore: bump version to 0.0.13

- .github/workflows/ci.yaml
- deploy/004-deploy-pool-registry.ts
- deploy/006-deploy-mock-pools.ts
- package.json
Fix deployments scripts by allowing deployer to set caps
> Fix deployment scripts

- contracts/Rewards/RewardsDistributor.sol
Add a more complete natspec for distributeBorrowerRewardToken
> [015] docs: update dev natspec for distributeBorrowerRewardToken

- contracts/RiskFund/IRiskFund.sol
- contracts/RiskFund/RiskFund.sol
- deploy/004-deploy-pool-registry.ts
- tests/hardhat/Fork/RiskFund.ts
Specify assets and min amount when swapping for base asset
> [022] fix: specify assets and min amount when swapping for base asset

- contracts/Pool/PoolRegistry.sol
- tests/hardhat/PoolRegistry.ts
This PR adds a few changes to PoolRegistry and pool registry tests, see the commit messages for details.
- Internal audit 020 (access controls in setPoolName)
> Pool registry setters rehaul

- contracts/RiskFund/RiskFund.sol
- tests/hardhat/Fork/RiskFund.ts
> docs: update nat spec

- .gitignore
- contracts/BaseJumpRateModelV2.sol
- contracts/Comptroller.sol
- contracts/VToken.sol
- deploy/004-deploy-pool-registry.ts
- Included `unchecked` flag for simple situation.
- Remove basic compiler warnings.
- Added .openZeppelin in .gitignore file.
> [IMP007] Unchecked Flag and compiler warnings.

- contracts/Comptroller.sol
- contracts/Pool/PoolRegistry.sol
- contracts/Rewards/RewardsDistributor.sol
- contracts/RiskFund/ProtocolShareReserve.sol
- contracts/Shortfall/Shortfall.sol
- contracts/VToken.sol
- tests/hardhat/PoolRegistry.ts
- tests/hardhat/Shortfall.ts
Peckshield Isolated Pools Audit fixes: https://www.notion.so/Peckshield-Isolated-Pools-730b237fdd47429d889f6bddc7d7a0b8
Resolves:
https://jira.toolsfdg.net/browse/VEN-853
https://jira.toolsfdg.net/browse/VEN-854
https://jira.toolsfdg.net/browse/VEN-855
https://jira.toolsfdg.net/browse/VEN-856
> fix: audit peckshield

- contracts/VToken.sol
- tests/hardhat/Tokens/borrowAndRepayTest.ts
Fixes the Frontrunning issue as part of the Audit.
> fix : PeckShield Audit PVE-002 (Frontrunning)

- deploy/002-price-oracle.ts
- deploy/003-price-oracle-configure-feeds.ts
- deploy/006-deploy-mock-pools.ts
- hardhat.config.ts
- tests/integration/index.ts
Resolves issues in integration test and corresponding deployment script.
> fix: integration test deployment scripts

- contracts/Comptroller.sol
- tests/hardhat/Comptroller/accountLiquidityTest.ts
> fix: peckShield audit PVE-004 (Sanity Checks)

- contracts/VToken.sol
- contracts/VTokenInterfaces.sol
- tests/hardhat/Tokens/setters.ts
Removes public comptroller setter as it will never be used
> refactor: remove public comptroller setter

- contracts/Rewards/RewardsDistributor.sol
Add total rewards available to distribution events
> feat: add reward totals to events

- contracts/Comptroller.sol
- contracts/Pool/PoolRegistry.sol
- contracts/Shortfall/Shortfall.sol
- tests/hardhat/Comptroller/assetsListTest.ts
- tests/hardhat/Comptroller/healAccountTest.ts
- tests/hardhat/Comptroller/hooks.ts
- tests/hardhat/Comptroller/pauseTest.ts
- tests/hardhat/Comptroller/setters.ts
- tests/hardhat/Shortfall.ts
This PR resolves:
VEN-1026: M05. Inconsistent Data - Unused Return Value
VEN-1027: M06. Best Practice Violation - Check Effects Interaction Pattern Violation
> Fix: Hacken audit issues

- contracts/BaseJumpRateModelV2.sol
- contracts/Comptroller.sol
- contracts/ComptrollerInterface.sol
- contracts/ComptrollerStorage.sol
- contracts/IPancakeswapV2Router.sol
- contracts/InterestRateModel.sol
- contracts/JumpRateModelV2.sol
- contracts/Pool/PoolRegistry.sol
- contracts/Pool/PoolRegistryInterface.sol
- contracts/Proxy/UpgradeableBeacon.sol
- contracts/Rewards/RewardsDistributor.sol
- contracts/RiskFund/ProtocolShareReserve.sol
- contracts/RiskFund/RiskFund.sol
- contracts/VToken.sol
- contracts/VTokenInterfaces.sol
- tests/hardhat/Rewards.ts
This PR resolves the following audit fixes:
- VEN-958: VPB-06 | Missing Zero Address Validation
- VEN-965: VPB-15 | Unneccessary Use of Payable Casting
- VEN-1009: VPB-10 | `initialize()` Is Unprotected And Inconsistent Init Function
- VEN-1028: M07. Contradiction - NatSpec Contradiction
- VEN-1029: M08. Contradiction - Name Contradiction
- VEN-1031: M10. Inconsistent Data - Missing Event for Critical Value Updates
- VEN-1033: M12. Contradiction - NatSpec Comments Contradiction
- VEN-1034: L01. Floating Pragma
- VEN-1035: L02. Redundant Import
- VEN-1036: L03. Missing Zero Address Validation
- VEN-1037: L05. Contradiction
> Hacken and Certik Audit Fixes

- contracts/BaseJumpRateModelV2.sol
- contracts/Comptroller.sol
- contracts/Governance/AccessControlManager.sol
- contracts/Lens/PoolLens.sol
- contracts/Rewards/RewardsDistributor.sol
- contracts/RiskFund/ProtocolShareReserve.sol
- contracts/RiskFund/ReserveHelpers.sol
- contracts/RiskFund/RiskFund.sol
- contracts/VToken.sol
- contracts/VTokenInterfaces.sol
- contracts/WhitePaperInterestRateModel.sol
VEN-1038: L06. Division by Zero
VEN-1039: L07. Style Guide Violation
VEN-1040: L08. Functions that Can Be Declared External
VEN-1041: L09. Boolean Equality
VEN-1042: L10. Variable Shadowing
VEN-1043: L11. Unindexed Events
VEN-1046: L14. Use of Hard-Coded Values
> Hacken audit fix

- .solhint.json
- .solhintignore
- contracts/BaseJumpRateModelV2.sol
- contracts/ComptrollerInterface.sol
- contracts/ComptrollerStorage.sol
- contracts/ExponentialNoError.sol
- contracts/JumpRateModelV2.sol
- contracts/Rewards/RewardsDistributor.sol
- contracts/RiskFund/IRiskFund.sol
- contracts/VToken.sol
- contracts/VTokenInterfaces.sol
- contracts/WhitePaperInterestRateModel.sol
- contracts/test/ComptrollerScenario.sol
- contracts/test/Const.sol
- contracts/test/ERC20.sol
- contracts/test/FaucetToken.sol
- contracts/test/FixedPriceOracle.sol
- contracts/test/InterestRateModelHarness.sol
- contracts/test/Mocks/MockPriceOracle.sol
- contracts/test/Mocks/MockToken.sol
- contracts/test/PriceOracleProxy.sol
- contracts/test/SimplePriceOracle.sol
- contracts/test/UpgradedVToken.sol
- contracts/test/VTokenHarness.sol
- contracts/test/WBTC.sol
This PR contains reordering based on solidity style guides and adds it to CI lint.
Resolves [VEN-1039]
> [VEN-1039] Reordering solidity style guide

- contracts/Comptroller.sol
- contracts/ComptrollerInterface.sol
- contracts/ComptrollerStorage.sol
- contracts/Rewards/RewardsDistributor.sol
* 963 and 967 Certik audit fix.
Resolves #
> [VEN-963, VEN-967] Certik audit 

- contracts/ExponentialNoError.sol
This PR resolves Hacken audit L12; removed unused functions in the contract.
Resolves #[VEN-1044]
> [VEN-1044] Hacken L12. Contract Should be Library

- .solhint.json
- contracts/Comptroller.sol
- contracts/ComptrollerStorage.sol
- contracts/MaxLoopsLimitHelper.sol
- contracts/Pool/PoolRegistry.sol
- contracts/Rewards/RewardsDistributor.sol
- contracts/RiskFund/RiskFund.sol
- contracts/test/HarnessMaxLoopsLimitHelper.sol
- deploy/006-riskfund-protocolshare.ts
- deploy/010-deploy-pools.ts
- tests/hardhat/AccessControl.ts
- tests/hardhat/Comptroller/accountLiquidityTest.ts
- tests/hardhat/Comptroller/assetsListTest.ts
- tests/hardhat/Comptroller/healAccountTest.ts
- tests/hardhat/Comptroller/hooks.ts
- tests/hardhat/Comptroller/liquidateCalculateAmountSeizeTest.ts
- tests/hardhat/Comptroller/pauseTest.ts
- tests/hardhat/Comptroller/setters.ts
- tests/hardhat/Fork/RiskFund.ts
- tests/hardhat/Fork/RiskFundSwap.ts
- tests/hardhat/MaxLoopsLimitHelper.ts
- tests/hardhat/PoolRegistry.ts
- tests/hardhat/Rewards.ts
- tests/hardhat/Shortfall.ts
- tests/hardhat/UpgradedVToken.ts
- tests/hardhat/lens/PoolLens.ts
> [VEN-1019][VEN-1022]Added loops limit.

- package.json
This new pre-release version will contain the latest updates to the deployment scripts made in https://github.com/VenusProtocol/isolated-pools/pull/165, https://github.com/VenusProtocol/isolated-pools/pull/168 and https://github.com/VenusProtocol/isolated-pools/pull/170
> v0.0.18-develop.2

- contracts/BaseJumpRateModelV2.sol
- contracts/ErrorReporter.sol
- contracts/InterestRateModel.sol
- contracts/JumpRateModelV2.sol
- contracts/VToken.sol
- contracts/VTokenInterfaces.sol
- contracts/WhitePaperInterestRateModel.sol
- contracts/test/InterestRateModelHarness.sol
- contracts/test/VTokenHarness.sol
- tests/hardhat/StableRateModel.ts
- tests/hardhat/Tokens/borrowAndRepayTest.ts
- tests/hardhat/Tokens/stableRateRebalancing.ts
- tests/hardhat/Tokens/swapBorrowRateMode.ts
This PR contains:
- Rebalancing conditions for the stable rate borrow.
- Tests for user to take borrow at both rates at a time.
- Swap rate mode with amount.
> [VEN-805][VEN-806][VEN-809][VEN-845]Stable rate rebalance

- contracts/Comptroller.sol
- contracts/RiskFund/ProtocolShareReserve.sol
Resolves - VEN-1024
- Added comments for the setMarketSupplyCaps and setMarketBorrowCaps.
> [VEN-1024]Added comments for the setMarketSupplyCaps and setMarketBorrowCaps.

- contracts/ErrorReporter.sol
- contracts/VToken.sol
- scenario/src/ErrorReporterConstants.ts
- tests/hardhat/Tokens/setters.ts
Resolves #
- VEN-1123: Encapsulate the ACM check in one function
> VEN-1123: Encapsulate the ACM check in one function.

- deploy/010-deploy-pools.ts
- deploy/012-transfer-ownership.ts
This PR adds a script to transfer ownership after deployment
Resolves # [VEN-1069]
> [VEN-1069] Transfer Ownership Script

- contracts/Comptroller.sol
- contracts/VToken.sol
- tests/hardhat/Comptroller/setters.ts
- tests/hardhat/Tokens/borrowAndRepayTest.ts
This PR fixes two small issues from certik audit. Please refer to the tickets for more information
Resolves # VEN-949  VEN-954
> Certik Audit fixes

- contracts/RiskFund/RiskFund.sol
- contracts/VToken.sol
- contracts/test/VTokenHarness.sol
- tests/hardhat/util/TokenTestHelpers.ts
**VEN-1204: L02. Redundant Import**
The RiskFund contract imports "../Pool/PoolRegistry.sol", "../Pool/PoolRegistryInterface.sol".
Recommendation: Remove the redundant import.
**VEN-1205: L08. Functions that Can Be Declared External**
Recommendation: Use the external attribute for functions never called from the contract.
Affected function: VToken.initialize()
> Hacken Audit Fixes

- contracts/ComptrollerInterface.sol
- contracts/Lens/PoolLens.sol
- tests/hardhat/Lens/PoolLens.ts
Add supply and borrow caps of markets to Pool Lens.
> [VEN-1207] feat: add supply and borrow caps to lens

- contracts/Shortfall/Shortfall.sol
- tests/hardhat/Shortfall.ts
Make waitForFirstBidder configurable
Resolves VEN-1243
> refactor: Make waitForFirstBidder configurable

- contracts/Shortfall/Shortfall.sol
- tests/hardhat/Shortfall.ts
Add start block to auction events so they auction can be easily identified by indexers
> refactor: Add start block to auction events

- contracts/Shortfall/Shortfall.sol
- tests/hardhat/Shortfall.ts
Make nextBidderBlockLimit configurable. Set default to 10 when initializing
Resolves VEN-1242
> [VEN-1242] feat: make nextBidderBlockLimit configurable

- contracts/Shortfall/Shortfall.sol
- tests/hardhat/Shortfall.ts
Make incentiveBps configurable
Resolves VEN-1245
> [VEN-1245] feat: make incentiveBps configurable

- contracts/BaseJumpRateModelV2.sol
- contracts/Comptroller.sol
- contracts/Governance/AccessControlled.sol
- contracts/Lens/PoolLens.sol
- contracts/Pool/PoolRegistry.sol
- contracts/RiskFund/IRiskFund.sol
- contracts/RiskFund/ProtocolShareReserve.sol
- contracts/RiskFund/RiskFund.sol
- contracts/Shortfall/Shortfall.sol
- contracts/WhitePaperInterestRateModel.sol
- deploy/009-deploy-pools.ts
- tests/hardhat/Fork/RiskFund.ts
- tests/hardhat/Fork/RiskFundSwap.ts
- tests/hardhat/Lens/PoolLens.ts
- tests/hardhat/Lens/RewardsSummary.ts
- tests/hardhat/PoolRegistry.ts
- tests/hardhat/Rewards.ts
- tests/hardhat/Shortfall.ts
- tests/hardhat/UpgradedVToken.ts
This PR adds fixes for the issues reported by Certik. See the commit messages for the details and references to each of the issues.
> Fixes for Certik report 04-2023

- contracts/Lens/PoolLens.sol
- contracts/Pool/PoolRegistry.sol
- contracts/Pool/PoolRegistryInterface.sol
- tests/hardhat/Lens/PoolLens.ts
- tests/hardhat/PoolRegistry.ts
This PR removes risk rating from VenusPolMetadata. We're not going to use it now, and it would be straightforward to add it in future if needed.
> feat!: [VEN-1385] Remove risk rating

- README.md
Add a message about the freezing of the code for the next public audit
> docs: add message about the freezing for the audit

- yarn.lock
Pin yarn to version 3 so dependencies can be resolved in a standard way
> chore: pin yarn version to 3.2.0

- contracts/Shortfall/Shortfall.sol
- tests/hardhat/Shortfall.ts
Adds toggle to turn auctions on and off.
> feat: add ability to toggle auctions on and off

- docgen-templates/page.hbs
Add doc gen support for contracts and templates
> docs: add doc gen support for contracts and templates

- contracts/Comptroller.sol
Resolves #
- VEN-1485
Oracle price is not updated for each asset inside _getHypotheticalLiquiditySnapshot.
> [VEN-1485]: Update oracle price for all tokens.

- deploy/012-riskfund-protocolshare.ts
The `typechain` types are built and not packages so they can't be referenced in packaged files. We can look into supporting building typechains at installation. For now this adds generic types and removes the dependency on typechain in the deployment scripts
> fix: remove dependency on typechain from deployments

- contracts/Comptroller.sol
- contracts/Pool/PoolRegistry.sol
- tests/hardhat/Comptroller/liquidateAccountTest.ts
- tests/hardhat/PoolRegistry.ts
Resolves #
- VEN-1559
- VEN-1560
> [Ven-1559] [VEN-1560]: require initial liquidity adding a market and avoid seizing on markets disabled as collateral

- .prettierignore
- package.json
Removes exports and lists desired packaged files
> refactor: remove exports key and list desired files

- contracts/Shortfall/Shortfall.sol
- contracts/test/MockDeflationaryToken.sol
- tests/hardhat/Shortfall.ts
> VEN-1459: Support for fee supporting tokens in shortfall

- contracts/Comptroller.sol
- contracts/ExponentialNoError.sol
- tests/hardhat/Comptroller/healAccountTest.ts
This reverts commit 8262af93f45f0d94122248984216ae0c40325c7f.
Resolves VEN-1591
> [VEN-1591]: Revert "fix: [VEN-1497]"

- contracts/BaseJumpRateModelV2.sol
- contracts/Comptroller.sol
- contracts/Shortfall/Shortfall.sol
- contracts/WhitePaperInterestRateModel.sol
Resolves #
- VEN-1587
- VEN-1589
- VEN-1590
> [VEN-1587] [VEN-1589] [VEN-1590]Fix: Minor code4Rena issues

- contracts/RiskFund/RiskFund.sol
- contracts/Shortfall/Shortfall.sol
- tests/hardhat/Shortfall.ts
Resolves:
- VEN-1494
- VEN-1510
> [VEN-1494] [VEN-1510] Fix: Minor issues.

- contracts/Shortfall/Shortfall.sol
- tests/hardhat/Shortfall.ts
Resolves:
- VEN-1493: Added strict validation for bidBps in shortfall contract 
- VEN-1500: Check for the auction start block
> [VEN-1493] [VEN-1500] Added checks in the shortfall contract

- contracts/VToken.sol
- tests/hardhat/Tokens/liquidateTest.ts
> [VEN-1628] Fix ProtocolSeizeTokens Calculation

- contracts/Pool/PoolRegistry.sol
- contracts/Rewards/RewardsDistributor.sol
- contracts/RiskFund/ProtocolShareReserve.sol
- contracts/RiskFund/ReserveHelpers.sol
- contracts/RiskFund/RiskFund.sol
Swap out @dev natspec for @notice on public and external items without a notice natspec
> refactor: swap @dev for @notice on public and external items

- contracts/test/Mocks/MockPriceOracle.sol
- tests/hardhat/Fork/RewardsForkTest.ts
> [VEN-1554][VEN-1555]: add fork tests for reward operations

- contracts/test/Mocks/MockPriceOracle.sol
- tests/hardhat/Fork/suppltTest.ts
- tests/hardhat/Fork/supply.ts
- tests/hardhat/Fork/utils.ts
Resolves #
- VEN-1551
- VEN-1552
> [Ven 1551] [VEN-1552]: Supply fork tests

- deploy/009-deploy-vtokens.ts
- deploy/011-initial-liquidity.ts
- deploy/012-transfer-pools-ownership.ts
- deploy/013-vip-based-config.ts
- helpers/deploymentUtils.ts
This PR fixes the issues identified by @chechu in [#245](https://github.com/VenusProtocol/isolated-pools/pull/245)
> chore: fix VIP deployment issues

- tests/hardhat/Fork/reduceReservesTest.ts
> [VEN-1553]: add fork tests of reserves

- contracts/PassiveSwap/AbstractSwapper.sol
- tests/hardhat/PassiveSwap/AbstractSwapper.ts
Resolves:
- VEN-1463
- VEN-1464
> [Ven 1463] [VEN-1464]: Abstract swapper methods(1/4)

- contracts/PassiveSwap/AbstractSwapper.sol
- tests/hardhat/PassiveSwap/AbstractSwapper.ts
Resolves 
- VEN-1465
- VEN-1466
> [VEN-1465] [VEN-1466] : Abstract swapper methods(2/4)

- contracts/PassiveSwap/AbstractSwapper.sol
- tests/hardhat/PassiveSwap/AbstractSwapper.ts
Resolves #
- VEN-1467
- VEN-1468
> [VEN-1467] [VEN-1468] : Abstract swapper methods(3/4)

- contracts/PassiveSwap/AbstractSwapper.sol
- contracts/PassiveSwap/IAbstractSwapper.sol
- contracts/test/Mocks/MockPriceOracle.sol
- contracts/test/Mocks/MockSwapper.sol
- package.json
- tests/hardhat/PassiveSwap/AbstractSwapper.ts
- yarn.lock
Resolves
- VEN-1469
- Added reenReentrancyGuard
- Added interface for AbstractSwapper
> [VEN-1469] : Abstract swapper methods(4/4)

- contracts/RiskFund/ProtocolShareReserve.sol
- contracts/RiskFund/ReserveHelpers.sol
- contracts/RiskFund/RiskFund.sol
- contracts/Shortfall/Shortfall.sol
- contracts/test/Mocks/MockPriceOracle.sol
- package.json
- tests/hardhat/Fork/RiskFund.ts
- tests/hardhat/Fork/RiskFundSwap.ts
- tests/hardhat/Fork/Shortfall.ts
- tests/hardhat/ProtocolShareReserve.ts
- tests/hardhat/Shortfall.ts
- tests/integration/index.ts
- yarn.lock
This PR adds converting the ruskFund balance into USD value rather than assuming that convertibleBaseAsset of the RiskFun is 1$
Resolves # VEN-1457
> [VEN-1457]: Shortfall: riskFundBalance should be in USD

- contracts/VToken.sol
> [VEN-1794]: Fairyproof fixes in Automatic income allocation August 1

- contracts/Comptroller.sol
> [VEN-1865]: add docs details about the latest changes in the supported RewardsDistributor

- contracts/VToken.sol
- contracts/VTokenInterfaces.sol
Certik fixes on Automatic Income Allocation
Resolves #VEN-1845
> [VEN-1845]: Certik fixes on AIA

- contracts/VToken.sol
- tests/integration/index.ts
4. [Low] Input Validation
Resolves #
> [VEN-1950]: Quantstamp audit fix on AIA

- contracts/Bridge/BaseXVSProxyOFT.sol
- contracts/Bridge/XVSBridgeAdmin.sol
- contracts/Bridge/token/TokenController.sol
> [VEN-2089]: PeckShield audit fixes on XVS bridge

- .github/workflows/ci.yaml
- README.md
- deployments/ethereum.json
- deployments/sepolia.json
- hardhat.config.ts
Update readme with information about deployed contracts and exporting deployments
> chore: add information about deployed contracts to readme

- contracts/test/lib/ProtocolShareReserve.sol
- deploy/014-riskfund-protocolshare.ts
- deploy/015-funds-config.ts
- deploy/015-transfer-funds-ownership.ts
- package.json
- tests/hardhat/Fork/RiskFund.ts
- tests/hardhat/Fork/RiskFundSwap.ts
- tests/integration/index.ts
- yarn.lock
The Protocol Share Reserve has been moved to its own repo so we can remove this deployment
> [VEN-2046]: refactor: remove protocol share reserve deployment

- deploy/015-funds-config.ts
- package.json
- yarn.lock
> [VEN-1825]: use the version with Token converters

- yarn.lock
> [VEN-1828]: update yarn.lock file

- deploy/009-deploy-vtokens.ts
- deploy/014-riskfund-protocolshare.ts
- deploy/015-funds-config.ts
- package.json
- tests/hardhat/Prime.ts
- tests/hardhat/Rewards.ts
- tests/hardhat/Shortfall.ts
- tests/hardhat/util/TokenTestHelpers.ts
- yarn.lock
Updates deployment scripts to work with protocol reserve deployment scripts
> fix: support breaking changes in protocol reserve deployment scripts

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
- funding.json
- yarn.lock
Atlas Optimisim funding verification
> chore: verify repo for Atlas Optimism

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
> chore: update actions/setup-node to v4

- contracts/ERC4626/VenusERC4626.sol
- tests/hardhat/ERC4626/VenusERC4626.ts
- tests/hardhat/Fork/VenusERC4626.ts
> [VEN-2887]: adjust the assets to be multiples of the VToken exchange rates
