VenusProtocol/isolated-pools

.gitignore, copy_contracts.sh, deploy/001-deploy-pool-registry.ts, deploy/002-deploy-pools.ts, hardhat.config.ts, package.json, yarn.lock
When running deploy scripts there is a discrepency with the build info included in the oracle package
and the build info hash generated when running the deploy scripts.
To get around this, after installing the contracts are copied directly from node_modules
=> Copy contracts to resolve build info conflict

Dockerfile, contracts/Pool/PoolRegistry.sol, tests/hardhat/PoolRegistry.ts
Events related to the pool should emit the same identifier for consistency. This id needs to match the id in the subgraph for easy querying. 
Since other events emit the pool index it is logic to use this as the id and emit it with all pool events. This PR updates the pool name set event to use the index as the identifier
=> Emit poolid with name set event

contracts/Lens/PoolLens.sol, contracts/Pool/PoolRegistry.sol, contracts/Pool/PoolRegistryInterface.sol, contracts/RiskFund/IRiskFund.sol, contracts/RiskFund/RiskFund.sol, contracts/Shortfall/Shortfall.sol, tests/hardhat/Fork/RiskFund.ts, tests/hardhat/PoolRegistry.ts, tests/hardhat/Rewards.ts, tests/hardhat/Shortfall.ts, tests/hardhat/UpgradedVBEP20.ts, tests/hardhat/lens/PoolLens.ts, tests/integration/index.ts
Events and functions accessing pools through index
have been refactored to use comptroller address
Accessers using poolID are removed
Mapping on shortfall for indexing with poolId has been removed
PoolId is no longer returned as it is used internally for looping over all pools only
=> refactor: make pool idx internal, comptroller as id

contracts/Comptroller.sol
This action isn't referenced anywhere else in the code so it can be removed.
=> fix: remove unused ActionPaused event

contracts/Governance/AccessControlManager.sol, contracts/Pool/PoolRegistry.sol, contracts/RiskFund/IProtocolShareReserve.sol, contracts/RiskFund/IRiskFund.sol, contracts/RiskFund/ProtocolShareReserve.sol, contracts/RiskFund/ReserveHelpers.sol, contracts/RiskFund/RiskFund.sol, contracts/VToken.sol, contracts/VTokenInterfaces.sol, tests/hardhat/Fork/RiskFund.ts, tests/hardhat/PoolRegistry.ts, tests/hardhat/ProtocolShareReserve.ts
This PR contains:
- Logic to handle the protocol share reserve and risk fund for multiple pools having same asset.
- Added tests for Risk fund and Protocol share reserve to test for multiple pools having same assets.
- Added a check for base asset (Stable asset in which all the assets will be swapped into, in risk fund) before swapping it with pancakeswap.
- Added setter(only owner) for the base asset in the Risk fund.
- Added access control check for the addMarket in the poolRegistry.
=> [VEN-783] Fix: Protocol share reserve for each market and add access control for addMarket.

contracts/Comptroller.sol, contracts/Lens/PoolLens.sol, contracts/Pool/PoolRegistryInterface.sol, contracts/Rewards/RewardsDistributor.sol, contracts/RiskFund/ReserveHelpers.sol, contracts/RiskFund/RiskFund.sol, contracts/Shortfall/Shortfall.sol, contracts/VToken.sol
This PR implements the following improvement suggestions from the internal audit report:
- **VENUS-IMP-001** ABICoder V2 Enabled By The Default After 0.8.x
- **VENUS-IMP-003** `++i` is cheaper than `i++`
- **VENUS-IMP-004** Caching array length can save gas
- **VENUS-IMP-005** Events are not indexed
- **VENUS-IMP-006** No need to initialize variables with default value
- **VENUS-IMP-008** Dont compare boolean expressions to boolean literals
- **VENUS-IMP-010** Use of power operations instead of their exponential form
Other improvement suggestions either need further discussion or will be addressed in the scope of a bigger refactoring (e.g. moving from error strings to custom error messages).
Note that "caching the error length" commit also moves some logic to separate internal functions …
=> Audit improvements, low-hanging fruits

contracts/Governance/AccessControlManager.sol, contracts/Rewards/RewardsDistributor.sol, contracts/RiskFund/RiskFund.sol, contracts/Shortfall/Shortfall.sol, tests/hardhat/Fork/RiskFund.ts, tests/hardhat/Shortfall.ts
This is a PR with the fixes for internal audit findings. By now, the following items are addressed:
* VENUS-001 Unused modifier
* VENUS-002 AccessControlManager can not revokeCallPermission if if contractAddress is zero
* VENUS-005 Use safeTransfer instead of transfer
* VENUS-008 Emit events when updating important state variables
=> Fixes for internal audit findings

contracts/BaseJumpRateModelV2.sol, contracts/Comptroller.sol, contracts/ComptrollerStorage.sol, contracts/ErrorReporter.sol, contracts/ExponentialNoError.sol, contracts/Rewards/RewardsDistributor.sol, contracts/Shortfall/Shortfall.sol, contracts/VToken.sol, contracts/WhitePaperInterestRateModel.sol
This PR locks the pragma to 0.8.13 for all production contracts except interfaces. The latter can potentially be imported from packages with a different compiler version, so we keep a floating ^0.8.10 for them.
=> fix: [009] lock pragma in non-interface contracts

contracts/VToken.sol
Bad debt is already tracked in healBorrow (with a bit different but similar math). This function also emits the corresponding event, so there's no point in keeping the unused method.
=> fix: remove unused function to track bad debt

contracts/Comptroller.sol, contracts/Pool/PoolRegistry.sol, contracts/Rewards/RewardsDistributor.sol, contracts/VToken.sol, contracts/VTokenInterfaces.sol, contracts/test/UpgradedVToken.sol, contracts/test/VTokenHarness.sol, deploy/001-deploy-pool-registry.ts, deploy/003-deploy-pools.ts, tests/hardhat/Comptroller/accountLiquidityTest.ts, tests/hardhat/Comptroller/assetsListTest.ts, tests/hardhat/Comptroller/healAccountTest.ts, tests/hardhat/Comptroller/liquidateCalculateAmountSeizeTest.ts, tests/hardhat/Comptroller/pauseTest.ts, tests/hardhat/Fork/RiskFund.ts, tests/hardhat/PoolRegistry.ts, tests/hardhat/Rewards.ts, tests/hardhat/Tokens/setComptrollerTest.ts, tests/hardhat/lens/PoolLens.ts, tests/integration/index.ts
This PR changes the function signatures so that they adhere to Solidity style guide:
* `_camelCase` for private and internal functions
* `camelCase` for regular functions, including access-controlled ones
Incidentally, this PR also changes type names in access controls to their canonical versions, and removes the return values from functions that just return Error.NO_ERROR. The remaining part of the error cleanup will be done in a separate PR.
Note that the changes are **BREAKING.**
Note that this PR **changes the access control mechanisms** in some places.
=> fix: [013] make function names adhere to Solidity style guide

contracts/Comptroller.sol, contracts/Pool/PoolRegistry.sol, contracts/RiskFund/ProtocolShareReserve.sol, contracts/RiskFund/RiskFund.sol, contracts/Shortfall/Shortfall.sol, contracts/VToken.sol, hardhat.config.ts, package.json, tests/hardhat/Comptroller/accountLiquidityTest.ts, tests/hardhat/Comptroller/assetsListTest.ts, tests/hardhat/Comptroller/healAccountTest.ts, tests/hardhat/Comptroller/liquidateCalculateAmountSeizeTest.ts, tests/hardhat/Comptroller/pauseTest.ts, tests/hardhat/Fork/RiskFund.ts, tests/hardhat/PoolRegistry.ts, tests/hardhat/ProtocolShareReserve.ts, tests/hardhat/Rewards.ts, tests/hardhat/Shortfall.ts, tests/hardhat/UpgradedVToken.ts, tests/hardhat/lens/PoolLens.ts, tests/hardhat/util/TokenTestHelpers.ts, yarn.lock
Problem: Uninitialized implementation may be initialized by an attacker if the contract is not deployed in the same transaction as proxy deployment or upgrade.
Solution: Add _disableInitializers call to the constructors. This affects tests, so this commit also updates tests (with some refactoring to replace unnecessary deployments with fakes).
Note that these changes are **BREAKING.** The corresponding commits are marked with `!`
Fixes the internal audit finding **012**.
**Note:** The PR is based on https://github.com/VenusProtocol/isolated-pools/pull/110 and marked as draft. The base should be changed to main and the PR can be marked as ready after https://github.com/VenusProtocol/isolated-pools/pull/110 is merged.
=> fix!: [012] add _disableInitializers to all upgradeable contracts

contracts/RiskFund/RiskFund.sol, deploy/004-deploy-pool-registry.ts, tests/hardhat/Fork/RiskFund.ts
Problem:
`swapAllAssets` could be called to fail maliciously.
Solution:
Add accessControlManager check to `swapAllAssets`
Note: 
I tried to keep using mocks in the tests but they weren't resetting properly so I deployed the contract and am revoking and setting permissions.
There was also a typo in the `transferReserveForAuction` signature string
=> [018] fix: add access control to swap pool asset

contracts/RiskFund/RiskFund.sol, tests/hardhat/Fork/RiskFund.ts
Update access control on `transferReserveForAuction` to only be callable by shortfall contract
=> [026] fix: set transferReserveForAuction to only be callable by shortfall

contracts/RiskFund/RiskFund.sol, package.json, tests/hardhat/Fork/RiskFundSwap.ts
Problem: Non-standard tokens like USDT will revert the transaction when a contract tries to approve an allowance when the spender allowance is already set a non-zero value. This can potentially lead to denial of service.
Solution: Approve zero before setting allowance to nonzero value.
=> fix: [017] approve zero before approving nonzero amount

contracts/Pool/PoolRegistry.sol, contracts/VToken.sol, contracts/VTokenInterfaces.sol, contracts/test/VTokenHarness.sol, deploy/004-deploy-pool-registry.ts, deploy/006-deploy-mock-pools.ts, tests/hardhat/Fork/RiskFund.ts, tests/hardhat/Fork/RiskFundSwap.ts, tests/hardhat/PoolRegistry.ts, tests/hardhat/Rewards.ts, tests/hardhat/UpgradedVToken.ts, tests/hardhat/lens/PoolLens.ts
When calling `addMarket` we need to provide `initialSupply`, `borrowCap` and `supplyCap`. The caller should approve `initialSupply` amount to the `PoolRegistry` before calling `addMarket`.
=> [010] Initial Supply for Markets

contracts/RiskFund/RiskFund.sol, tests/hardhat/Fork/RiskFund.ts
Riskfund Contract and Shortfall Contract both need the other's address to be set in order for them to be deployed, but neither contract has a setter to do so. As a result, deployment of both contracts became impossible. Shortfall Contract has a setter named setAuctionContrcatAddress rather than setShortfallContractAddress.
Shortfall contract use transferReserveForAuction function internally it transfers fund to auctionContract instead of shortfall contract, It should be a shortfall contract rather than an auction contract.
Because we are using smock, we have been unable to detect this serious problem until now in tests, which are conducted separately for the two contracts.
=> Riskfund auction_contract updated with shortfall_contract

.eslintrc.js, deploy/001-deploy-mock-tokens.ts, helpers/utils.ts, tests/hardhat/Comptroller/accountLiquidityTest.ts, tests/hardhat/Fork/RiskFundSwap.ts, tests/hardhat/Rewards.ts, tests/hardhat/Shortfall.ts, tests/hardhat/Tokens/accrueInterestTest.ts, tests/hardhat/Tokens/borrowAndRepayTest.ts, tests/hardhat/Tokens/liquidateTest.ts, tests/hardhat/Tokens/mintAndRedeemTest.ts, tests/hardhat/lens/PoolLens.ts, tests/integration/index.ts
It includes :
**Liquidation scenario on straight path:** (VEN-884)
- via Comptroller
- via vToken
**Heal Account Scenario:** (VEN-885)
- Revert scenarios
- Success Scenarios
=> Integration test for [VEN-884] Liquidation and [VEN-885] Heal Account scenarios

.eslint-tsconfig, contracts/Comptroller.sol, contracts/Governance/AccessControlManager.sol, contracts/Shortfall/Shortfall.sol, contracts/VToken.sol, docgen-templates/common.hbs, docgen-templates/helpers.ts, docgen-templates/properties.ts, hardhat.config.ts
This PR updates the docgen template for autogenerating documentation.
It will render custom event, access, and error tags as a list.
It only renders entities marked as external or public
```
Sender redeems vTokens in exchange for the underlying asset
```solidity
function redeem(uint256 redeemTokens) external returns (uint256)
```
| Name | Type | Description |
| ---- | ---- | ----------- |
| redeemTokens | uint256 | The number of vTokens to redeem into underlying |
| Name | Type | Description |
| ---- | ---- | ----------- |
| [0] | uint256 | error Always NO_ERROR for compatilibily with Venus core tooling |
* Emits Redeem and Transfer events; may emit AccrueInterest
* Not restricted
* RedeemTransferOutNotPossible is thrown when the protocol has insufficient cash
- - -
```
=> [VEN-893] Update doc template with custom tags

contracts/Comptroller.sol, tests/hardhat/Comptroller/setters.ts, tests/hardhat/Rewards.ts
This event is required to listen to Reward Distributor events such as `DistributedSupplierRewardToken`  and `DistributedBorrowerRewardToken`
=> feat: add event for new rewards distributor

contracts/VToken.sol, contracts/VTokenInterfaces.sol, contracts/test/Mocks/MockPancakeSwap.sol, tests/hardhat/Tokens/mintAndRedeemTest.ts, tests/integration/index.ts
This PR aims to make the Mint and Redeem VToken events also return the updated value for the account balance. This can make the subgraph save calling the `balanceOf` function everytime it indexes these events.
=> feat: Mint and Redeem events emit the updated account balance

contracts/Comptroller.sol, contracts/ComptrollerInterface.sol, contracts/Lens/PoolLens.sol, tests/hardhat/lens/RewardsSummary.ts
This PR adds functionality to get pending rewards for a certain user (for all markets) for a given pool.
Resolves : VEN-883
=> [VEN-883] Get Rewards for a user

contracts/Comptroller.sol, contracts/Factories/VTokenProxyFactory.sol, contracts/JumpRateModelV2.sol, contracts/Lens/PoolLens.sol, contracts/Pool/PoolRegistry.sol, contracts/Pool/PoolRegistryInterface.sol, contracts/Rewards/RewardsDistributor.sol, contracts/RiskFund/IRiskFund.sol, contracts/RiskFund/ProtocolShareReserve.sol, contracts/RiskFund/ReserveHelpers.sol, contracts/RiskFund/RiskFund.sol, contracts/Shortfall/IShortfall.sol, contracts/Shortfall/Shortfall.sol, contracts/VToken.sol, contracts/test/VTokenHarness.sol, helpers/utils.ts, tests/hardhat/Fork/RiskFund.ts, tests/hardhat/Fork/RiskFundSwap.ts, tests/hardhat/ProtocolShareReserve.ts, tests/hardhat/Tokens/transferTest.ts
Resolves the following Certik report fixes:
- VEN-962 VTV-03 | Approval Race Condition
- VEN-965 VPB-15 | Unneccessary Use of Payable Casting
- VEN-972 VPB-12 | Missing Access Restriction
- VEN-971 VPB-11 | Missing or Unused Emit Events
- VEN-968 JRM-01 | Unnecessary Inheritance
- VEN-955 VPB-04 | Interfaces Not Inherited And Improper/Missing Implementation
- VEN-916 VTV-02 | `mintBehalf()` Can Mint Tokens to the Zero Address
- VEN-958 VPB-06 | Missing Zero Address Validation
- VEN-960 VPB-08 | Changing `convertibleBaseAsset` Can Cause Issues
=> Certik Audit Fixes

contracts/Pool/PoolRegistry.sol
**Problem:** The code fails for tokens with underlying decimals < 8. Additionally, the code assumes that vTokens always have 8 decimals, and although it's a correct assumption, we should have a protection in case someone configures input.decimals to be a different number.
**Solution:** Change the order of operations and replace 8 with the provided decimals value.
=> fix: prevent decimals underflow in exchange rate computation

deploy/006-riskfund-protocolshare.ts, tsconfig.json
This PR replaces the ERC20 artifact to not use typechain, but the prebuilt contract of OZ, thus increasing usability of the deployment scripts from other packages.
Resolves #[VEN-1092]
=> [VEN-1092] import ERC20 abit from openzeppelin build

contracts/Comptroller.sol, contracts/ComptrollerStorage.sol
Resolves:
- CVP-05 | Storage Variables Declared Outside of `ComptrollerV1Storage
=> [VEN-967] Moved variables from comptroller to comptroller storage.

contracts/Shortfall/Shortfall.sol, tests/hardhat/Shortfall.ts
Removes access controls for starting and restarting auctions as any one can start an auction as long as the conditions are met
=> refactor: remove access controls on auctions

contracts/RiskFund/RiskFund.sol, tests/hardhat/Fork/RiskFund.ts, tests/hardhat/Fork/RiskFundSwap.ts
Makes poolReserves public for transparency
Resolves [VEN-1246]
=> [VEN-1246] refactor: make poolReserves public on RiskFund

contracts/RiskFund/IRiskFund.sol, contracts/RiskFund/RiskFund.sol, deploy/008-access-control-configure.ts, tests/hardhat/Fork/RiskFund.ts, tests/hardhat/Fork/RiskFundSwap.ts
This PR adds an array of swap paths to the `swapPoolsAsset` method. This allows for multiple hops in the swap allowing better optimization for price
Resolves [VEN-1248]
=> [VEN-1248] Refactor: add path to swapPoolAssets

contracts/Pool/PoolRegistry.sol, tests/hardhat/PoolRegistry.ts
This PR updates PoolRegistry so that it supplies the actual transferred amount to vTokens when someone adds a new market to the pool
=> feat: support deflationary tokens in addMarket

contracts/Comptroller.sol, tests/hardhat/Comptroller/accountLiquidityTest.ts, tests/hardhat/Comptroller/liquidateAccountTest.ts, tests/integration/index.ts
This PR includes:
1. use _getLiquidationThreshold instead of _getCollateralFactor in the current Comptroller.getAccountLiquidity
2.define a new view Comptroller.getBorrowingPower, similar to Comptroller.getAccountLiquidity , but using _getCollateralFactor
liquidation tests pass and liquidity tests are extended to also check getBorrowingPower
Resolves #[VEN-1527]
=> [VEN-1527]: new Comptroller.getBorrowingPower view

contracts/Comptroller.sol, contracts/ExponentialNoError.sol, tests/hardhat/Comptroller/healAccountTest.ts, tests/hardhat/Comptroller/pauseTest.ts
VEN-1495: MaxLoopLimitHelper._ensureMaxLoop() is validating the wrong input in Comptroller.setActionsPaused()
VEN-1496: Comptroller.sol#preBorrowHook can be exploited to bypass maxLoopsLimit
VEN-1497: Reject healAccount when ratio collateral/scaledBorrows is 1
Resolves VEN-1495, VEN-1496, VEN-1497
=> [VEN-1495] [VEN-1496] [VEN-1497]: Fix/code4rena medium issues

package.json
In this PR we allow node engines newer than 16.x. This would allow other packages to use `isolated-pools` as a dependency even if their required node version is greater than 16.
=> chore: allow newer engines

deploy/013-vip-based-config.ts, package.json
This PR modifies the build script to first generate typings for the contracts and then build TypeScript. The second commit adds the missing typings to fix ts compilation.
Note: there's a `fix` commit to trigger a release.
=> fix: generate typings before building typescript

contracts/BaseJumpRateModelV2.sol, tests/hardhat/JumpRateModelV2.ts, tests/integration/index.ts
Problem: The new IL JumpRateModel is based on Compound's updated version. The problem with that is that the multiplier is divided by kink in this updated version. This is counterintuitive and inconsistend with the core pool behavior.
Solution: Use the classic computation, i.e. not divide the slope by kink.
=> feat: use core pool behavior for jump rate multiplier

contracts/RiskFund/IRiskFund.sol, contracts/RiskFund/RiskFund.sol, contracts/Shortfall/Shortfall.sol, tests/hardhat/Fork/RiskFund.ts, tests/hardhat/Fork/RiskFundSwap.ts, tests/hardhat/Shortfall.ts
Resolves #1743
* Removed `poolReserves` (Slot no 306) mapping in Risk Fund.
* Change slot numbers for `pancakeSwapRouter` and `minAmountToConvert` from **302,303** to **304,305**
* Update `assetsReserves[convertableBaseAsset]` and `poolsAssetsReserves[comptroller][convertableBaseAsset]` whenever`swapPoolsAssets` is called.
* Refactored tests.
**Previous RiskFund Layout Storage Snippet** 
**Current RiskFund Storage Layout Snippet**
=> [VEN-1743]: Refactor Risk Fund storage layout

contracts/VToken.sol, contracts/VTokenInterfaces.sol, tests/hardhat/Fork/RiskFund.ts, tests/hardhat/Fork/RiskFundSwap.ts
3.1.1 Changes in VTokenInterface.IncomeType (IL) - Removed unused enum
3.1.2 Rest of suggestions in VTokenInterface.sol (IL) - Removed unused events
3.2.1 VToke.reduceReserves kind param (IL) - Removed kind parameter from reduceReserves() function
3.2.2 VToken reinitializer(2) (IL) - Reverted	
3.2.3 VToken.healBorrow and RepayBorrow event (IL)-	We treat healing as "repayment”
Additionally, the comptroller only call healBorrow while there is borrowBalance in the market, therefore if repayAmount is 0 then also badDebtDelta block will be executed.
3.2.4 VToken._redeemFresh (IL)-It gives flexibility to user to redeem any number of tokens, if the amount resulted be zero it will fail [here](https://github.com/VenusProtocol/isolated-pools/blob/fix/fairyproof-audit-fixes/contracts/VToken.sol#L916) …
=> Fairyproof audit fixes of VToken Automatic Income Allocation

contracts/RiskFund/IRiskFund.sol, contracts/RiskFund/RiskFund.sol, tests/hardhat/Fork/RiskFund.ts, tests/hardhat/Fork/RiskFundSwap.ts
Problem: When we swap pools' assets we must protect ourselves against transaction delays – miners may want to delay the execution of our transaction to potentially gain profits from a changing exchange rate.
Solution: Add `deadline` parameter that would invalidate the transaction if it's executed after the deadline is passed.
Note: I had to remove the local vToken variable to avoid stack too deep error. Although the code is less readable now, other solutions I could come up with (e.g. the standard one – introduce a struct SwapLocalVars {...} containing the local variables for the function) harm readability even more.
Resolves VEN-1703
=> [VEN-1703]: support deadline in swapPoolsAssets

contracts/Shortfall/Shortfall.sol, contracts/lib/TokenDebtTracker.sol, contracts/test/lib/TokenDebtTrackerHarness.sol, tests/hardhat/lib/TokenDebtTracker.ts
Problem: Shortfall contract transfers tokens to previous bidders on placeBid. This might lock the auction if the receiver can not receive a transfer due to some reason, e.g. if the receiver is blacklisted in the token contract.
Solution: Track the tokens owed to users due to failed transfer attempts.
Resolves #VEN-1477
=> [VEN-1477]: avoid locking on failed transfers to previous bidders

contracts/Comptroller.sol, tests/hardhat/Fork/Shortfall.ts, tests/integration/index.ts
Resolves #1817
Peckshield audit fix PVE-003
=> [VEN-1817] Peckshield audit fix PVE-003

contracts/RiskFund/ProtocolShareReserve.sol, contracts/RiskFund/ReserveHelpers.sol, contracts/RiskFund/RiskFund.sol, contracts/Shortfall/Shortfall.sol, contracts/lib/ApproveOrRevert.sol, contracts/test/lib/ApproveOrRevertHarness.sol, tests/hardhat/Fork/RiskFund.ts, tests/hardhat/lib/ApproveOrRevert.ts
This PR fixes the findings identified by Certik in their 2023-08 audit of PSR, RiskFund and Shortfall contracts.
=> [VEN-1798]: Fix Certik 2023-08 findings for PSR/RiskFund/Shortfall contracts

contracts/Comptroller.sol, contracts/ComptrollerStorage.sol, tests/hardhat/Comptroller/liquidateAccountTest.ts
=> [VEN-1930]: forced liquidation

contracts/Comptroller.sol, contracts/ComptrollerInterface.sol, contracts/ComptrollerStorage.sol, contracts/ErrorReporter.sol, contracts/VToken.sol, tests/hardhat/Tokens/borrowAndRepayTest.ts, tests/hardhat/Tokens/mintAndRedeemTest.ts
This PR:
- removes support for redemption allowances in favor of deletate (operator) contracts
- adds tests for delegate redemptions
- updates some natspecs so that they correspond with the declarations
=> fix: delegate borrowing/redemption fixups for VEN-2356

contracts/legacy/RiskFund/IRiskFund.sol, contracts/legacy/RiskFund/ReserveHelpers.sol, contracts/legacy/RiskFund/RiskFund.sol
Adds back legacy risk fund ABI to allow interacting with the previous version of the risk fund contract. Useful for services like the subgraph
=> refactor: add legacy riskfund contract

.github/workflows/cd.yaml, .github/workflows/ci.yaml
=> [VEN-3175]: replace the gh action not valid anymore

deploy/009-deploy-vtokens.ts, helpers/deploymentConfig.ts, helpers/deploymentUtils.ts
Problem: Currently whether the deployment is time-based is defined by the environment variable. This is error-prone and requires us to support corner cases like having both `blocksPerYear` configured and `timeBased` flag set to true.
Solution: Make "time-based" a property of a particular network. For hardhat, support both modes based on the environment variable.
=> refactor: make "time-based" a property of the network
